version: "3.5"

services:

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - db_vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build: .
    command: >
      sh -c 'python /code/bin/wait_for_it.py -a db -p 5432 --
          python example/manage.py makemigrations &&
          python example/manage.py migrate &&
          python example/manage.py loaddata admin &&
          python example/manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_vol: ~
