version: "3.5"

services:

  db:
    image: postgres
    container_name: django-reactive
    restart: always
    volumes:
    - "./data/pgdata:/var/lib/postgresql/data"
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: postgres
      POSTGRES_DB: tests
      PGDATA: /var/lib/postgresql/data/pgdata
