# Generated by Django 3.2.16 on 2022-12-29 05:02

from django.db import migrations, models
import django_reactive.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AlternativesExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternatives', django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='Alternatives')),
            ],
        ),
        migrations.CreateModel(
            name='ArraysExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrays', django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='Arrays')),
            ],
        ),
        migrations.CreateModel(
            name='BasicExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='Basic example')),
            ],
        ),
        migrations.CreateModel(
            name='DateAndTimeExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'date_and_time',
                    django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='Date and time'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ErrorsExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errors', django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='Errors')),
            ],
        ),
        migrations.CreateModel(
            name='FileTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='Files')),
            ],
        ),
        migrations.CreateModel(
            name='LargeExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large', django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='Large')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='First field')),
                ('second', django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='Second field')),
            ],
        ),
        migrations.CreateModel(
            name='NestedExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nested', django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='Nested')),
            ],
        ),
        migrations.CreateModel(
            name='NumbersExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='Numbers')),
            ],
        ),
        migrations.CreateModel(
            name='OrderingExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='Ordering')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDependenciesExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'property_dependencies',
                    django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='Property dependencies'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ReferencesExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('references', django_reactive.fields.ReactJSONSchemaField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaDependenciesExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'schema_dependencies',
                    django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='Schema dependencies'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ValidationExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation', django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='Validation')),
            ],
        ),
        migrations.CreateModel(
            name='WidgetExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widgets', django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='Widgets')),
            ],
        ),
    ]
