# Generated by Django 2.0.9 on 2018-12-02 11:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_reactive.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', django_reactive.fields.ReactJSONSchemaField(default=dict, help_text='A field to test react-json-schema-form widget.')),
                ('test_widget', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='A field to test react-json-schema-form widget.')),
            ],
        ),
    ]
